
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 22 19:30:49 IST 2016
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface CUP_FILESym {
  /* terminals */
  public static final int INTEGER = 6;
  public static final int SWAP = 5;
  public static final int error = 1;
  public static final int PLUS = 2;
  public static final int ROW_ID = 7;
  public static final int MINUS = 3;
  public static final int EOF = 0;
  public static final int ASSIGN = 4;
}

