
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 08 17:44:37 IST 2016
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface CUP_FILESym {
  /* terminals */
  public static final int DIVIDE = 5;
  public static final int LCBR = 29;
  public static final int LTE = 35;
  public static final int INTEGER = 25;
  public static final int SEMI = 44;
  public static final int LPAREN = 6;
  public static final int CONTINUE = 14;
  public static final int INT = 24;
  public static final int MINUS = 3;
  public static final int STATIC = 45;
  public static final int RPAREN = 7;
  public static final int LT = 34;
  public static final int LP = 28;
  public static final int COMMA = 13;
  public static final int CLASS = 11;
  public static final int RP = 43;
  public static final int MULTIPLY = 37;
  public static final int PLUS = 2;
  public static final int QUOTE = 47;
  public static final int ASSIGN = 8;
  public static final int IF = 23;
  public static final int THIS = 48;
  public static final int DOT = 15;
  public static final int ID = 22;
  public static final int EOF = 0;
  public static final int BOOLEAN = 9;
  public static final int RETURN = 42;
  public static final int RCBR = 41;
  public static final int LB = 27;
  public static final int LAND = 26;
  public static final int EQUAL = 16;
  public static final int TRUE = 49;
  public static final int NEW = 31;
  public static final int error = 1;
  public static final int RB = 40;
  public static final int LOR = 33;
  public static final int NULL = 39;
  public static final int NUMBER = 52;
  public static final int MOD = 36;
  public static final int BREAK = 10;
  public static final int VOID = 50;
  public static final int GTE = 21;
  public static final int TIMES = 4;
  public static final int ELSE = 18;
  public static final int WHILE = 51;
  public static final int NEQUAL = 38;
  public static final int CLASS_ID = 12;
  public static final int EXTENDS = 17;
  public static final int STRING = 46;
  public static final int LNEG = 32;
  public static final int FALSE = 19;
  public static final int GT = 20;
  public static final int LENGTH = 30;
}

