
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 29 00:53:26 IST 2016
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface MatrixSym {
  /* terminals */
  public static final int INTEGER = 6;
  public static final int error = 1;
  public static final int SEMI = 5;
  public static final int DIVIDE = 2;
  public static final int LB = 3;
  public static final int RB = 4;
  public static final int EOF = 0;
}

