
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 22 19:52:43 IST 2016
//----------------------------------------------------

import java_cup.runtime.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Tue Nov 22 19:52:43 IST 2016
  */
public class OperationsCup extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public OperationsCup() {super();}

  /** Constructor which sets the default scanner. */
  public OperationsCup(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public OperationsCup(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\006\000\002\002\005\000\002\002\004\000\002\002" +
    "\005\000\002\002\003\000\002\004\003\000\002\004\002" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\010\000\002\001\002\000\010\002\ufffe\004\ufffe\005" +
    "\ufffe\001\002\000\010\002\010\004\006\005\007\001\002" +
    "\000\002\001\002\000\002\001\002\000\004\002\000\001" +
    "\002\000\010\002\uffff\004\uffff\005\uffff\001\002\000\010" +
    "\002\001\004\001\005\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\010\000\006\002\004\003\003\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\003\011\001\001\000\004" +
    "\003\010\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$OperationsCup$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$OperationsCup$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$OperationsCup$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$OperationsCup$actions {
  private final OperationsCup parser;

  /** Constructor */
  CUP$OperationsCup$actions(OperationsCup parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$OperationsCup$do_action(
    int                        CUP$OperationsCup$act_num,
    java_cup.runtime.lr_parser CUP$OperationsCup$parser,
    java.util.Stack            CUP$OperationsCup$stack,
    int                        CUP$OperationsCup$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$OperationsCup$result;

      /* select the action based on the action number */
      switch (CUP$OperationsCup$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // term ::= 
            {
              Integer RESULT =null;

              CUP$OperationsCup$result = parser.getSymbolFactory().newSymbol("term",2, ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.peek()), RESULT);
            }
          return CUP$OperationsCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // term ::= INTEGER 
            {
              Integer RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.peek()).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$OperationsCup$stack.peek()).value;
		 RESULT = n; 
              CUP$OperationsCup$result = parser.getSymbolFactory().newSymbol("term",2, ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.peek()), RESULT);
            }
          return CUP$OperationsCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // expr ::= factor 
            {
              Integer RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.peek()).right;
		Integer f = (Integer)((java_cup.runtime.Symbol) CUP$OperationsCup$stack.peek()).value;
		 RESULT = new Integer(f.intValue());                
              CUP$OperationsCup$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.peek()), RESULT);
            }
          return CUP$OperationsCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // expr ::= expr MINUS factor 
            {
              Integer RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.elementAt(CUP$OperationsCup$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.elementAt(CUP$OperationsCup$top-2)).right;
		Integer e = (Integer)((java_cup.runtime.Symbol) CUP$OperationsCup$stack.elementAt(CUP$OperationsCup$top-2)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.peek()).right;
		Integer f = (Integer)((java_cup.runtime.Symbol) CUP$OperationsCup$stack.peek()).value;
		 RESULT = new Integer(e.intValue() - f.intValue()); 
              CUP$OperationsCup$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.elementAt(CUP$OperationsCup$top-2)), ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.peek()), RESULT);
            }
          return CUP$OperationsCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= expr EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.elementAt(CUP$OperationsCup$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.elementAt(CUP$OperationsCup$top-1)).right;
		Integer start_val = (Integer)((java_cup.runtime.Symbol) CUP$OperationsCup$stack.elementAt(CUP$OperationsCup$top-1)).value;
		RESULT = start_val;
              CUP$OperationsCup$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.elementAt(CUP$OperationsCup$top-1)), ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$OperationsCup$parser.done_parsing();
          return CUP$OperationsCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // expr ::= expr PLUS factor 
            {
              Integer RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.elementAt(CUP$OperationsCup$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.elementAt(CUP$OperationsCup$top-2)).right;
		Integer e = (Integer)((java_cup.runtime.Symbol) CUP$OperationsCup$stack.elementAt(CUP$OperationsCup$top-2)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.peek()).right;
		Integer f = (Integer)((java_cup.runtime.Symbol) CUP$OperationsCup$stack.peek()).value;
		 RESULT = new Integer(e.intValue() + f.intValue()); 
              CUP$OperationsCup$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.elementAt(CUP$OperationsCup$top-2)), ((java_cup.runtime.Symbol)CUP$OperationsCup$stack.peek()), RESULT);
            }
          return CUP$OperationsCup$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

