
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 10 19:23:53 IST 2015
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 5;
  public static final int DIVIDE = 4;
  public static final int NUMBER = 8;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int error = 1;
  public static final int RPAREN = 7;
  public static final int TIMES = 3;
  public static final int LPAREN = 6;
}

